spring.application.name=RiziGo
amadeus.api.key=oa0a2bxc5R3no4Eqt3Gk4w1gYLpxEyFw
amadeus.api.secret=nfFmw2q4owdQbd0z
spring.datasource.url=jdbc:mysql://localhost:3306/rizigo_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Raezy66@
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

spring.security.user.name=admin
spring.security.user.password=admin
